import type { RepoNode, ActionType } from '../types';

export const sampleNodes: RepoNode[] = [
  // Tier 0 — Spines (locked)
  { id: 'phenotype-registry', name: 'phenotype-registry', lang: 'rust', tier: 0, description: 'INDEX/Ecosystem catalog', locked: true, x: 100, y: 50 },
  { id: 'OmniRoute', name: 'OmniRoute', lang: 'go', tier: 0, description: 'AI gateway (Go/TS)', locked: true, x: 300, y: 50 },
  { id: 'phenotype-apps', name: 'phenotype-apps', lang: 'typescript', tier: 0, description: 'Apps mono (iOS + web shell)', locked: true, x: 500, y: 50 },
  { id: 'phenotype-shared', name: 'phenotype-shared', lang: 'rust', tier: 0, description: 'Cross-language contracts', locked: true, x: 700, y: 50 },
  { id: 'pheno', name: 'pheno', lang: 'rust', tier: 0, description: 'Multi-crate Rust monorepo', locked: true, x: 900, y: 50 },
  { id: 'heliosApp', name: 'heliosApp', lang: 'typescript', tier: 0, description: 'Helios shell', locked: true, x: 1100, y: 50 },
  { id: 'helios-cli', name: 'helios-cli', lang: 'rust', tier: 0, description: 'CLI', locked: true, x: 1300, y: 50 },
  { id: 'Eidolon', name: 'Eidolon', lang: 'rust', tier: 0, description: 'Agent runtime', locked: true, x: 1500, y: 50 },
  { id: 'phenoAI', name: 'phenoAI', lang: 'rust', tier: 0, description: 'AI workspace', locked: true, x: 1700, y: 50 },
  { id: 'Substrate', name: 'Substrate', lang: 'rust', tier: 0, description: 'Large integration hub', locked: true, x: 1900, y: 50 },
  { id: 'shareCLI', name: 'shareCLI', lang: 'rust', tier: 0, description: 'Shared CLI framework', locked: true, x: 2100, y: 50 },

  // Tier 1 — Active Research
  { id: 'pheno-tracing', name: 'pheno-tracing', lang: 'rust', tier: 1, description: 'Sampling-policy port + tracing substrate', x: 100, y: 220 },
  { id: 'PhenoCompose', name: 'PhenoCompose', lang: 'rust', tier: 1, description: 'Unified Process Compose with NVMS Support', x: 300, y: 220 },
  { id: 'PhenoContracts', name: 'PhenoContracts', lang: 'html', tier: 1, description: 'Phenotype contract verification', x: 500, y: 220 },
  { id: 'phenodag', name: 'phenodag', lang: 'go', tier: 1, description: 'Multi-agent multi-project DAG', x: 700, y: 220 },
  { id: 'phenoData', name: 'phenoData', lang: 'rust', tier: 1, description: 'BLOCK A app (phenoData)', x: 900, y: 220 },
  { id: 'phenoEvents', name: 'phenoEvents', lang: 'rust', tier: 1, description: 'PhenoEvents: EventBus port', x: 1100, y: 220 },
  { id: 'PhenoHandbook', name: 'PhenoHandbook', lang: 'shell', tier: 1, description: 'Phenotype Handbook - patterns, anti-patterns', x: 1300, y: 220 },
  { id: 'phenokits-commons', name: 'phenokits-commons', lang: 'python', tier: 1, description: 'Cross-cutting commons', x: 1500, y: 220 },
  { id: 'PhenoMCP', name: 'PhenoMCP', lang: 'rust', tier: 1, description: 'PhenoMCP: MCP server integration toolkit', x: 1700, y: 220 },
  { id: 'PhenoMCPServers', name: 'PhenoMCPServers', lang: 'python', tier: 1, description: 'Phenotype MCP implementations registry', x: 1900, y: 220 },
  { id: 'PhenoObservability', name: 'PhenoObservability', lang: 'rust', tier: 1, description: 'Phenotype-org observability primitives', x: 2100, y: 220 },
  { id: 'PhenoProject', name: 'PhenoProject', lang: 'typescript', tier: 1, description: 'Phenotype PhenoProject domain workspace', x: 100, y: 380 },
  { id: 'phenoResearchEngine', name: 'phenoResearchEngine', lang: 'python', tier: 1, description: 'Phenotype research and investigation engine', x: 300, y: 380 },
  { id: 'phenotype-go-sdk', name: 'phenotype-go-sdk', lang: 'go', tier: 1, description: 'Phenotype-org Go SDK', x: 500, y: 380 },
  { id: 'phenotype-hub', name: 'phenotype-hub', lang: 'javascript', tier: 1, description: 'Phenotype org hub (governance scaffold)', x: 700, y: 380 },
  { id: 'phenotype-infra', name: 'phenotype-infra', lang: 'go', tier: 1, description: 'Compute mesh', x: 900, y: 380 },
  { id: 'phenotype-journeys', name: 'phenotype-journeys', lang: 'rust', tier: 1, description: 'Reusable journey harness', x: 1100, y: 380 },
  { id: 'phenotype-landing', name: 'phenotype-landing', lang: 'astro', tier: 1, description: 'Monorepo: all landing pages', x: 1300, y: 380 },
  { id: 'Grapheon', name: 'Grapheon', lang: 'rust', tier: 1, description: 'Canonical Grapheon repository', x: 1500, y: 380 },
  { id: 'Melosviz', name: 'Melosviz', lang: 'python', tier: 1, description: 'Music-to-visual toolkit', x: 1700, y: 380 },
  { id: 'PhenoRuntime', name: 'PhenoRuntime', lang: 'rust', tier: 1, description: 'PhenoRuntime - active', x: 1900, y: 380 },
  { id: 'FocalPoint', name: 'FocalPoint', lang: 'svelte', tier: 1, description: 'Dependency management (cargo-deny)', x: 2100, y: 380 },
  { id: 'KDesktopVirt', name: 'KDesktopVirt', lang: 'rust', tier: 1, description: 'AI Agent Desktop Automation', x: 100, y: 540 },
  { id: 'kmobile', name: 'kmobile', lang: 'rust', tier: 1, description: 'KMobile - mobile CLI/API/MCP', x: 300, y: 540 },

  // Tier 3 — Ugly Names / Cleanup Candidates
  { id: 'phenotype-pm-core', name: 'phenotype-pm-core', lang: 'rust', tier: 3, description: 'PM/quality mono (alias phenopm)', x: 100, y: 700 },
  { id: 'phenotype-router-spec', name: 'phenotype-router-spec', lang: 'rust', tier: 3, description: 'Router spec content', x: 300, y: 700 },
  { id: 'phenotype-org-governance', name: 'phenotype-org-governance', lang: 'rust', tier: 3, description: 'Org governance scaffold', x: 500, y: 700 },
  { id: 'portage-temp', name: 'portage-temp', lang: 'rust', tier: 3, description: 'Temp marker', x: 700, y: 700 },
  { id: 'rich-cli-kit', name: 'rich-cli-kit', lang: 'rust', tier: 3, description: 'Recovery artifact', x: 900, y: 700 },
  { id: 'pheno-port-adapter', name: 'pheno-port-adapter', lang: 'rust', tier: 3, description: 'Recovery artifact', x: 1100, y: 700 },
  { id: 'pheno-runtime-config', name: 'pheno-runtime-config', lang: 'rust', tier: 3, description: 'Recovery artifact', x: 1300, y: 700 },
  { id: 'pheno-forge-plugins', name: 'pheno-forge-plugins', lang: 'rust', tier: 3, description: 'Recovery artifact', x: 1500, y: 700 },
];

export const seedEdges: { source: string; target: string; action: ActionType; note: string }[] = [
  { source: 'pheno-tracing', target: 'PhenoObservability', action: 'merge', note: 'tracing substrate into observability' },
  { source: 'phenoData', target: 'phenotype-apps', action: 'merge', note: 'BLOCK A app into apps collection' },
  { source: 'PhenoHandbook', target: 'phenotype-hub', action: 'merge', note: 'patterns into governance scaffold' },
  { source: 'PhenoMCPServers', target: 'PhenoMCP', action: 'merge', note: 'registry alongside MCP toolkit' },
  { source: 'phenotype-router-spec', target: 'phenotype-registry', action: 'merge', note: 'spec into registry docs' },
  { source: 'phenotype-pm-core', target: '__delete__', action: 'delete', note: 'temp alias' },
  { source: 'portage-temp', target: '__delete__', action: 'delete', note: 'temp marker' },
  { source: 'rich-cli-kit', target: '__delete__', action: 'delete', note: 'recovery artifact' },
  { source: 'pheno-port-adapter', target: '__delete__', action: 'delete', note: 'recovery artifact' },
  { source: 'pheno-runtime-config', target: '__delete__', action: 'delete', note: 'recovery artifact' },
  { source: 'pheno-forge-plugins', target: '__delete__', action: 'delete', note: 'recovery artifact' },
  { source: 'phenotype-org-governance', target: 'phenotype-registry', action: 'rename', note: 'merge governance into registry' },
  { source: 'phenotype-go-sdk', target: '__archive__', action: 'archive', note: 'needs decomposition per user directive' },
  { source: 'PhenoRuntime', target: '__archive__', action: 'archive', note: 'archived placeholder' },
];
